import type { Metadata } from "next";
import { Outfit } from "next/font/google";

import "overlayscrollbars/overlayscrollbars.css";
import "./globals.css";
import Providers from "@/hooks/providers";

const outfit = Outfit({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outfit.className} h-dvh text-sm break-words text-gray-600 antialiased md:text-base`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
