import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import 'overlayscrollbars/overlayscrollbars.css';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });
// export const playfair = Playfair_Display({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${inter.className} text-sm antialiased h-dvh break-words text-gray-600`}
      >
        {children}
      </body>
    </html>
  );
}
